### PR TITLE
Feat/gatsby starter ts

### PR DESCRIPTION
**Pull request by ricokahler**
This is an attempt to build a stater from our discussion in #43.

This is draft PR and is _not_ ready to merge.

This PR does two things:

1. takes the default gatsby starter and converts it to typescript with codegen
2. add a workflow to build it in CI.

I don't know if this will work or not, so thus the draft 🤷‍♀️🤞

### CODE REVIEW

**Comment by ricokahler** [comment]
image

Okay this is currently _not_ working but it's a start! I'll try some things in the coming days.

**Comment by d4rekanguok** [comment]
Nice work! I tried a different workflow config, where the we ran the `gatsby build` from the workspace root instead. It worked, but now I ran into issue with graphql module resolution. 

>  Error: Cannot use GraphQLScalarType "JSON" from another module or realm.
  Ensure that there is only one instance of "graphql" in the node_modules
  directory. If different versions of "graphql" are the dependencies of other
  relied on modules, use "resolutions" to ensure only one version is installed.
  https://yarnpkg.com/en/docs/selective-version-resolutions
  Duplicate "graphql" modules cannot be used at the same time since different
  versions may have different capabilities and behavior. The data from one
  version used in the function from another could produce confusing and
  spurious results.

It seems to be an issue only with running build from inside a workspace. If I copy `gatsby-starter-ts` to its own directory, then the build command runs successfully.

**Comment by d4rekanguok** [comment]
- The resolution error was caused by having multiple versions of Gatsby in the repo — downgraded `gatsby-starter-ts`'s Gatsby to 2.9.2 fixed the issues.
- Setting `tsconfig.target` to 'esnext' prevent Typescript from transforming nullish coalescing operator & optional chaining. Downgrading to `ES2018` seems to fix the issue. Should add this bit in the readme.
- Typecheck is going crazy with 3rd party @types def! I have turned it off just to get this action working, but for testing purpose we should re-enable it.

The action is working now though! 🎉

**Comment by ricokahler** [comment]
> The action is working now though! 🎉

Nice work!

I opened another temporary branch in #48 just to play around with some settings and not completely mess up the history. I see that the build is working but I'm not seeing any info from `gatsby-plugin-graphql-codegen`

I expected to see this line in the build output:

```
info [gatsby-plugin-graphql-codegen] definition for queries has been updated at graphql-types.ts
``` 

but it's not there leading me to think it's not running the local version of `gatsby-plugin-graphql-codegen` from the repo.

Would you know if this is working or not? I'm unfamiliar with yarn workspaces but I'm learning from your setup.

**Comment by d4rekanguok** [comment]
Oh it was running before, perhaps turning on CI surpressed the log?

**Comment by d4rekanguok** [comment]
Alright, we just need to get typecheck working and this is ready to merge.

**Pull request merged**
